name: example
description: An example for Habitat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  binarize: ^1.5.0
  flame: ^1.10.0
  flutter:
    sdk: flutter
  habitat:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
