name: example
description: An example for Habitat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  binarize: ^1.0.1
  flame: ^1.2.0
  flutter:
    sdk: flutter
  habitat:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
