name: habitat
description: A new Flutter project.
version: 0.1.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies: 
  fast_noise: ^1.0.1
  vector_math: ^2.1.2

dev_dependencies:
  coverage: ^1.1.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
