name: habitat
description: Generate any kind of world by defining biomes and attributes.
version: 0.1.0-dev.1
repository: https://github.com/wolfenrain/habitat

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  collection: ^1.16.0
  fast_noise: ^2.0.0
  meta: ^1.7.0

dev_dependencies:
  coverage: ^1.6.4
  test: ^1.24.7
  very_good_analysis: ^5.1.0
