name: habitat
description: Generate any kind of world by defining biomes and attributes.
version: 0.1.0-dev.1
repository: https://github.com/wolfenrain/habitat

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  collection: ^1.16.0
  fast_noise: ^1.0.1
  meta: ^1.7.0
  vector_math: ^2.1.2

dev_dependencies:
  coverage: ^1.1.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
