name: habitat

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/habitat.yaml
      - lib/**
      - test/**
      - pubspec.yaml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/habitat.yaml
      - lib/**
      - test/**
      - pubspec.yaml

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed lib test

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Ensure Build
        run: dart test --run-skipped -t pull-request-only

  build:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Run Tests
        run: |
          dart pub global activate coverage 1.2.0
          dart test -j 1 -x pull-request-only --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1

  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana

      - name: Verify Pub Score
        run: |
          PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
          echo "score: $PANA_SCORE"
          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
          if (( $SCORE < $TOTAL )); then echo "minimum score not met!"; exit 1; fi